// REMOVE: import axios from 'axios';
// REMOVE: import { Order } from '../types';
// REMOVE: const API_URL = ...
// REMOVE: const apiClient = ...
// REMOVE: export const orderApi = ...
// REMOVE: export const departmentApi = ...